version: '3.5'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27010:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db
    networks:
      - backend
networks:
  backend:
    external:
      name: proxy
